### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by nullrndtx** [Kintaro/wtftw#102]
Hey, i really love it this WM.. But, can WTFTW use another bar like yabar, polybar, lemonbar, or etc?

**Comment by Kintaro** [comment]
Yes. I tried yabar at one point. Lemonbar should also work, just depends how you configure it.
So far I've used: lemonbar, yabar, xmobar. If I can find them, I can create a gist with an example config.

**Comment by nullrndtx** [comment]
@Kintaro i try to use yabar but yabar create new windows as other applications.. i hope you'll adding that feature, till now i still using WTFTW. Great works! btw :+1:

**Comment by Kintaro** [comment]
You need to tell yabar to act as a dock. Yabar is not setting struts right.
But a good alternative is polybar.
