### ISSUE TITLE
Losing keyboard on Debian Jessie

### ISSUE THREAD

**Issue by steveklabnik** [Kintaro/wtftw#17]
I run pretty basic Debian Jessie on my ThinkPad, and `wtftw` seems to have a weird behavior: after a while, the only thing that can use the keyboard is firefox.

Steps:
1. Use `wtftw` for a while. Everyhing works just fine.
2. at some point, bad stuff happens
3. Notice that you can't switch workspaces, use `xmobar`, or even quit. Typing in text boxes in Firefox works, though.

I'm using the stock config file, just pointing at my own xmobarrc.

**Comment by Limvot** [comment]
Just wanted to mention that I am experiencing the same not-responding-to-keys behavior on Arch on my lenovo thinkpad with the most recent version of wtftw and rustc. It's really cool otherwise!

**Comment by steveklabnik** [comment]
Which thinkpad? I have a T440s.

**Comment by Kintaro** [comment]
Only instance when wtftw doesn't respond to keys anymore is when it crashes silently. Some xorg versions then revert back to your display manager or to tty. Some others remain active, so you can still see the open windows and interact with them, but wtftw is gone, so it can't react to shortcuts anymore.

Unfortunately I'm a bit busy with my thesis, but I'll try to stabilize it as much as I can as soon as possible.

**Comment by Limvot** [comment]
W540! Ah, gotcha. That makes sense. Thanks!

**Comment by Limvot** [comment]
I feel a little silly and apologise for possibly wasting your time: after running it through gdb I found that it was hanging on the "match p.write().unwrap().stdin.as_mut() {" line from my configuration (copied from the default configuration). After commenting it out, I've had no problems. Thanks!

**Comment by Kintaro** [comment]
Ah, so maybe you didn't have xmobar installed or something like that?

@steveklabnik what if you remove the bottom part of the config, the one about xmobar? Is it still happening then?

**Comment by steveklabnik** [comment]
I'll try it sometime, don't have time right now.

**Comment by Kintaro** [comment]
No hurry ^^ Busy myself.

**Comment by Limvot** [comment]
That's actually the odd part! I do have xmobar installed and it works fine, and I now just start it separately.

**Comment by FreeFull** [comment]
Also note keyboard shortcuts won't work while capslock is on, sometimes I accidentally press capslock and wonder why I can't switch workspaces anymore.

**Comment by coyotebush** [comment]
I also see it hanging on writing to xmobar after a few minutes, as confirmed through a [few extra debug statements](https://github.com/coyotebush/config/blob/9fcac169dd6d3c96892cd5b0483249ac318c040d/wtftw/src/config.rs#L162-169). Will see if I can figure out whether it's the RwLock or the Writer that gets stuck. (Debian Jessie, ThinkPad X220 here.)

**Comment by coyotebush** [comment]
So given [these debug statements](https://github.com/coyotebush/config/blob/90fa158eece0957bfb6bc22da9a89706b29748a8/wtftw/src/config.rs#L162-L178), the last thing in the log when it hangs is consistently "got stdin". Also, a few minutes before that happens, the StdinReader display in xmobar goes blank. Makes me think the pipe is getting clogged somehow, so to speak.

**Comment by FreeFull** [comment]
What does the xmobar config look like?

**Comment by coyotebush** [comment]
My [xmobar config](https://github.com/coyotebush/config/blob/master/xmobarrc) is also in that repository.

**Comment by steveklabnik** [comment]
So, trying this again, and when I start x, it just errors out. The only `EE` line in my log is

    [ 42333.458] (EE) Server terminated successfully (0). Closing log file.


Sooooo unsure what's up with that. I have just this as my .xinitrc:

    exec /home/steve/src/target/release/wtftw

Running it like in the readme works just fine.

**Comment by steveklabnik** [comment]
(and wtftw.log doesn't have anything, and i wiped my config)

**Comment by Kintaro** [comment]
I'll try to figure out what the problem is. As for the log file: since the log macro crate changed to being immutable I can't create and write to a log file anymore. Will have to write my own logging mechanisms for that.

**Comment by datagrok** [comment]
I'm seeing something similar but different in Debian testing (stretch). Upon launching wtftw under Xephyr and letting Xephyr grab the keyboard and mouse, some keybindings in wtftw seem to work fine (MOD1+Shift+Enter, MOD1+q, MOD1+Shift+q) but others don't (MOD1+h and MOD1+l in particular.)

Also, to make any debug logging output happen at all, I had to add the `env_logger` crate and call `env_logger::init().unwrap();` in `fn main()`. Using rustc 1.7.0-nightly (4744472fe 2016-01-02), wtftw commit 00d3dac.
