### ISSUE TITLE
Suggestions, enhancements and other notes. :-)

### ISSUE THREAD

**Issue by james-darkfox** [Kintaro/wtftw#32]
Hello Kintaro, loving your window manager; intend to switch away from XMonad! Although, before I do; I'd like to make a number of suggestions, enhancements and other notes. :-)

Layout notes
------------
- Fullscreen looks better without borders
- Resizing panes is fun, but better when you can resize both axises. (I.e. Shift for the other)
- Spacing variable is ignored; is this meant to be the gap between the windows and the screen's edges?

BYO panel?
----------
- A problem that I've had with xmobar is that it doesn't compile into XMonad, it would be nice to see a bar that compiles into the window manager.
- Integration means that we don't need to redraw the entire bar when any single component changes; I.e. A clock ticking.
- Overloaded panel? Prompt for running programs, notifications or dynamically setting various variables (I.e. MPD_HOST env variable for MPD related functions; which works very well for audio controls).

Expanding on keyboard keys?
---------------------------
- Wouldn't it be nice if we could do for example "M-s-&lt;Return&gt;" or scan for delayed keys for combinations such as "M-s a" to have M-s for search; and a for ArchWiki.
- Not sure if this could be expanded through using macros? Hopefully so.

Window groups/border colours
----------------------------
- Something that I've considered for a while is having various border colours for windows in different groups; I.e. As a class or role associated to the window.
- An example for where this is useful is when you have various jails/chroots with different networking rules or file access.
- Active colour could be a modifier (I.e. +#222222) and would apply against any underlying colour.

Potential libraries for wtftw-contrib ;-)
-----------------------------------------
- Rust bindings to libmpd (for tighter integration and less shell I/O).
- Tmux listing and auto attaching; like <https://github.com/vodik/dotfiles/blob/master/xmonad/lib/XMonad/Util/Tmux.hs>.
- Each of the above 3 sections (panel,keyboard,window-groups) if modular enough.

-

Sadly; I'm a bit too rusty with rust; I'm learning and I'm looking into the layout suggestions currently. :)
P.S: Great to hear that Wayland is also a possibility as it would mean that the efforts for X continue to be of value when people switch to Wayland. ^,^ Oh and Merry Christmas!

-DarkFox

**Comment by james-darkfox** [comment]
Ahem; kintaro; this "issue" was a collection of many ideas...

**Comment by Kintaro** [comment]
And they are noted. They will come back as separate issues that I'll work on.

**Comment by james-darkfox** [comment]
:-)
