### ISSUE TITLE
Input and focus problems 

### ISSUE THREAD

**Issue by skade** [Kintaro/wtftw#50]
I have an issue on FreeBSD with XOrg. All Input works, but the windows don't gain focus until I press "CapsLock". Then, I can write to a window, but with the issue that everything is all-caps. Am I just using things wrong or missing something or is this a bug?

The platform is FreeBSD/XOrg... :trollface:

**Comment by Kintaro** [comment]
Ok, 10.1 is set up, rust is compiled, just waiting for the static cargo binary. I tried to compile it, but somehow I can't get git2-rs compiled.
