### ISSUE TITLE
if the config.rs has an error wtftw is stuck

### ISSUE THREAD

**Issue by diefans** [Kintaro/wtftw#55]
I am playing around with wtftw...

I created a `/usr/share/xsessions/wtftw.desktop` file which points to a bash script in `/usr/bin/wtftw` which in turn calls `RUST_LOG='debug' /home/code/wtftw/target/wtftw` 

when I put an error into my config.rs wtftw is stuck after logging it cannot compile the config.

**Comment by diefans** [comment]
that is nice!

beside this, the whole restart takes a lot of time e.g. after showing `updating dependencies` in the log.

From a user perspective it's missing something, showing the progress and calming down the user that he has not been forgotten...

**Comment by Kintaro** [comment]
There seems to be an issue with "cargo update" lately. I don't know why that is.
The compilation itself shouldn't take that long (except when wtftw itself was updated). Seems to be a regression bug in rustc. I've noticed the slowdown too. Still trying to figure out how to minimize it with the least amount of assumptions about the system.
