### ISSUE TITLE
Window tags instead of workspaces

### ISSUE THREAD

**Issue by Yamakaky** [Kintaro/wtftw#56]
Hi.
Did you consider switching to tags instead of workspaces ? I find them much more usefull (as you can do workspaces with tags). It was a major point for me not to switch from awesome to xmonad.

**Comment by Kintaro** [comment]
Dafuq is up with Github, seriously?! I've responded like 2 times already.
So, it should be possible through config extensions. There's also a xmonad extension called TagWindows, which seems like the thing you're going for. So, theoretically it should be possible. 
To be honest, I've never used awesome or i3 before, so I can't really say anything about it. But I've set up a few virtual machines to take a peek at other tiling window managers. As soon as I'm done with my thesis I'll take a closer look. I've already "ported" bspwm's binary tree layout (minus the mouse interaction). I can't promise anything yet, but from a first look it seeems realizable as an extension. So I'' mark it a a future feature.
