### ISSUE TITLE
wtftw_core fails to build

### ISSUE THREAD

**Issue by drmugg123** [Kintaro/wtftw#62]
I'm using the latest rust nightly, rustc 1.0.0-nightly (4db0b3246 2015-02-25) (built 2015-02-26)
and the latest cargo, cargo 0.0.1-pre-nightly (5773064 2015-02-25) (built 2015-02-25)

And here's the build log:
http://pastebin.com/pUrENWnX

**Comment by drmugg123** [comment]
I'm not proficient enough in rust to know what's wrong, sorry

**Comment by Kintaro** [comment]
It should work now. It was due to the log crate missing a commit. The PR has been merged now and log was pushed to crates.io https://github.com/rust-lang/log/commit/d4b2f54758738adcda3162ff09adfb1a2caa8d53

**Comment by FreeFull** [comment]
The Cargo.lock file should probably be updated.

**Comment by Kintaro** [comment]
Yep, but I had to wait until the push was out. Lock is updated https://github.com/Kintaro/wtftw/commit/0c76245720c6604aa4223de031d701086d668d27
