### ISSUE TITLE
unable to start terminal

### ISSUE THREAD

**Issue by rainerborene** [Kintaro/wtftw#68]
Now that #67 issue was closed I have got another issue.
```
thread '<unnamed>' panicked at 'unable to start terminal', core/src/handlers.rs:48
```
I'm running wtftw on Xephyr using the default config.

**Comment by Kintaro** [comment]
In the default config this is set to xterm. Do you have your own config in ~/.wtftw/src/config.rs?

**Comment by rainerborene** [comment]
Just moved the default config to `~/.wtftw/src/config.rs` but it does not compile. See the log file.
https://gist.github.com/rainerborene/8c36618bd0390af33094

**Comment by Kintaro** [comment]
Let me update the default config when I get to work. Will be in about 1 hour. Hang in tight, fix is in the way.

**Comment by Kintaro** [comment]
Ok, the example config has been updated. I hope it works now.

**Comment by rainerborene** [comment]
Thanks!
