### ISSUE TITLE
readme's setup of config/config.rs skips addition of wtftw-contrib dependency

### ISSUE THREAD

**Issue by nathanross** [Kintaro/wtftw#70]
I've created this as an issue instead of a pull-request because I'm not sure which resolution would be preferred.

Issue: The README's provided workflow for making use of a custom configuration is: 

 1. run wtftw, which creates ```~/.wtftw/```
 * copy repository's ```/config/config.rs``` to the created config dir under ```~/.wtftw/src/```
 * try out / adjust to taste.

This workflow causes a build error / the configuration is unused because the default ```~/.wtftw/Cargo.toml``` does not have wtftw-contrib as a dependency. Some users will not know how to quickly fix this.

Here are three possible resolutions:

 1. add wtftw-contrib as a dependency in the default Cargo.toml even though the default configuration doesn't require it. 
 * create a full configuration dir in ```/config``` and instruct users to copy over the entire dir
 * explain in the readme that the example config requires the addition of the wtftw-contrib dependency (and optionally how to add dependencies to the Cargo.toml, using wtftw-contrib as an example)

**Comment by Kintaro** [comment]
Oh right, thanks. Option 1 seems best. Will add it as soon as I grt back from work.
