### ISSUE TITLE
Use json file for configuration instead of config.rs

### ISSUE THREAD

**Issue by nxnfufunezn** [Kintaro/wtftw#73]
Move configuration file to ~/.config/.wtftw dir and use json file for easy configuration instead of config.rs which requires compilation every-time config changes

**Comment by Kintaro** [comment]
That is exactly the point of the config.rs
To make the config programmable and extensible with more plugins.

**Comment by FreeFull** [comment]
Using a .json file would severely limit how the user can customise the window manager.

**Comment by Kintaro** [comment]
Closing as the point of the config is to be compilable and runnable.
