### ISSUE TITLE
Java GUI appears blank

### ISSUE THREAD

**Issue by ruhlio** [Kintaro/wtftw#79]
XMonad has a `SetWMName` (http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Hooks-SetWMName.html) function as a workaround to prevent Java GUIs (AWT I believe) from appears as only a gray rectangle. In my case, Intellij fails to paint. As a first pass I tried, inside of `XlibWindowSystem::new()` changing
`let name = (*CString::new(&b"wtftw"[..]).unwrap()).as_ptr();`
to
`let name = (*CString::new(&b"LG3D"[..]).unwrap()).as_ptr();`
but the issue still remained.

**Comment by Kintaro** [comment]
```
export _JAVA_AWT_WM_NONREPARENTING=1
```

This should fix it

**Comment by ruhlio** [comment]
Setting the environment variable didn't work but calling `wmname LG3D` did. Thanks

**Comment by Kintaro** [comment]
Ok. For me the env variable helped with IntelliJ. But if that works too, great :D

**Comment by hryniuk** [comment]
In `config.rs`:
```rust
run!("wmname", "LG3D")(w, w, w);
```

**Comment by bitemyapp** [comment]
I had to do `wmname LG3D` for Xmonad to get Intellij to work, it's a pretty common problem.
