### ISSUE TITLE
Tagging for release

### ISSUE THREAD

**Issue by steveno** [Kintaro/wtftw#82]
Have you considered tagging a certain commit as a "stable release" yet? 

I'd like to start using the project but, frankly, I don't want to have to follow rust master. I was thinking that while DEV could follow rust master you could tag releases that correspond to rust releases. At least for now anyway. I assume the project (and rust itself) will eventually reach a point where it won't matter which version of rust as long as its 1.X or greater.

**Comment by Kintaro** [comment]
Done

**Comment by steveno** [comment]
Awesome!
