### ISSUE TITLE
Add EWMH support to wtftw

### ISSUE THREAD

**Issue by nxnfufunezn** [Kintaro/wtftw#86]
EWMH Atoms Supported --
- [x]  _NET_SUPPORTING_WM_CHECK
- [x]  _NET_WM_NAME
- [x]  _NET_WM_STRUT
- [x]  _NET_WM_STRUT_PARTIAL
- [x]  _NET_WM_WINDOW_TYPE_DOCK
- [x]  _NET_WM_WINDOW_TYPE_DESKTOP
- [x]  _NET_WM_WINDOW_TYPE
- [x]  _NET_CURRENT_DESKTOP
- [x]  _NET_NUMBER_OF_DESKTOPS
- [x]  _NET_ACTIVE_WINDOW
- [ ]  _NET_DESKTOP_NAMES
- [ ]  _NET_CLIENT_LIST
- [ ]  _NET_WORKAREA
- [ ]  _NET_WM_ALLOWED_ACTIONS
- [ ]  _NET_WM_STATE
- [ ]  _NET_WM_WINDOW_TYPE_DIALOG
- [ ]  _NET_CLOSE_WINDOW
- [ ]  _NET_ACTIVE_WINDOW
- [ ]  _NET_WM_VISIBLE_NAME

**Comment by nxnfufunezn** [comment]
@Kintaro any additions to this

**Comment by jonhoo** [comment]
`_NET_DESKTOP_VIEWPORT` would be really handy (see xmonad discussion over at https://github.com/xmonad/xmonad-contrib/issues/150#issuecomment-359295241)
