### ISSUE TITLE
"*" version requirements

### ISSUE THREAD

**Issue by yberreby** [Kintaro/wtftw#87]
https://github.com/Kintaro/wtftw/blob/master/xlib/Cargo.toml#L8-L10

```
[dependencies]
log = "*"
libc = "*"
x11 = { version = "*", features = ["xlib", "xinerama"] }
```

Unless I missed something, if `log`, `libc` or `x11` release a new major version with breaking changes, your code will cease to compile. Is there a particular reason why you aren't specifying a stricter version requirement that would allow semver-compatible upgrades, but not breaking changes?

**Comment by Kintaro** [comment]
Until it hits stable, I will keep the xlib interface tracking the current packages. Once I'm satisfied with the xlib interface, I will lock it.
