### ISSUE TITLE
How to start wtftw? xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)

### ISSUE THREAD

**Issue by imShara** [Kintaro/wtftw#89]
How to start this?

My `.xinitrc`: `exec wtftw`
Starting X as user: `xinit -- :1 -nolisten tcp vt$XDG_VTNR`
Xserver error: `xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)`

**Comment by Kintaro** [comment]
Hm, that is strange. I usually start it via my dm. But it seems more like a permission issue
