### ISSUE TITLE
Build fails with latest rust nightly

### ISSUE THREAD

**Issue by imranmunshi** [Kintaro/wtftw#93]
With the current stable release of rust (in Arch official repo) wtftw builds with messages like <code>this warning results from recent bug fixes and clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details</code>.

May be something worth fixing.

My environment has rust version 1:1.5.0-1, cargo version 0.7.0-1.

Thank You!

**Comment by Kintaro** [comment]
Any specific line it complains about? Not running arch, so something to
reproduce it would help. Which file, which line.

Will do my best to fix it.

**Comment by imranmunshi** [comment]
With <code>wtftw</code> (1.2-1) from AUR, here are the errors:
<code>==> Starting build()...
unused manifest key: profile.debug.codegen-units
unused manifest key: profile.debug.lto
   Compiling rustc-serialize v0.3.15
   Compiling bitflags v0.1.1
   Compiling libc v0.1.8
/home/imunshi/.cargo/registry/src/github.com-88ac128001ac3a9a/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 error: the trait `core::marker::Sized` is not implemented for the type `Self` [E0277]
/home/imunshi/.cargo/registry/src/github.com-88ac128001ac3a9a/rustc-serialize-0.3.15/src/serialize.rs:201     fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error>;
                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/imunshi/.cargo/registry/src/github.com-88ac128001ac3a9a/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 help: run `rustc --explain E0277` to see a detailed explanation
/home/imunshi/.cargo/registry/src/github.com-88ac128001ac3a9a/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 note: `Self` does not have a constant size known at compile-time
/home/imunshi/.cargo/registry/src/github.com-88ac128001ac3a9a/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 note: required by `core::result::Result`
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `rustc-serialize`.

To learn more, run the command again with --verbose.
==> ERROR: A failure occurred in build().</code>

Not really related to your code I guess. In the git version (wtftw-git) the build fails for rand since rustc-serialize v0.3.16 is used on the git version it build successfully. If rand and other libraries have newer versions then it might be useful to use them if they have rectified build issues with latest nightly.
