### ISSUE TITLE
error: struct `KeyModifiers` is private

### ISSUE THREAD

**Issue by askobara** [Kintaro/wtftw#95]
when try to compile `~/.wtftw` with `rustc 1.9.0-nightly (e91f889ed 2016-03-03)`

**Comment by pierrechevalier83** [comment]
I am experiencing the same thing. I am working on a fix.
(BTW, it is not only with nightly rustc: also with 1.7, stable)

**Comment by Kintaro** [comment]
Ah, I fixed this, but not pushed yet. At least it works on nightly. Work keeps me away from being active at the moment.
