### ISSUE TITLE
are you planning on supporting redox-os?

### ISSUE THREAD

**Issue by vitiral** [Kintaro/wtftw#97]
Redox-OS is the operating system written in rustlang. They could really use a simple tiling window manager!

https://github.com/redox-os/redox

Also, how would you compare this to i3wm?

**Comment by Kintaro** [comment]
I'll start with the last question: wtftw is more akin to xmonad than it is to i3wm.

I followed the redox os dev blog, but I haven't taken a detailed look at the code so far. I would love to support redox-os. How long it would take and how difficult it would be depends on the graphics and event system.

**Comment by Kintaro** [comment]
Oh, I just realized: it would be possible, but only in its default configuration. For loading the config, it would need cargo and rustc at hand.

**Comment by vitiral** [comment]
Possible out of the box? That's great! Thanks for the info, feel free to cloae

**Comment by Kintaro** [comment]
Not out of the box. It would still need a new trait implementation. At the moment there is only the x.org implementation. 

The last comment was just to note that at the moment it wouldn't be possible to configure wtftw, as the config needs a compiler.

**Comment by Kintaro** [comment]
Closing for now
