### ISSUE TITLE
gnome-terminal doesn't draw at all

### ISSUE THREAD

**Issue by dpzmick** [Kintaro/wtftw#98]
Here's what I get when I start `gnome-terminal`

Very possibly an issue with some configuration that I have, but I'm not sure where to even begin looking, and suggestions?

![image](https://cloud.githubusercontent.com/assets/536697/17650462/60cbdd74-6214-11e6-84e5-eb6ab6977410.png)

**Comment by Kintaro** [comment]
Try using compton in the background. That should fix it. I still don't know why that is happening though.

**Comment by Kintaro** [comment]
And sorry for the late reply. I though I answered through my phone, but maybe the connection was bad.

**Comment by Kintaro** [comment]
Closing for now
